### ISSUE TITLE
Change the prompts in the home page

### ISSUE THREAD

**Issue by skounis** [morethanthemes/docs#72]
1. Installation (internal link)
2. Themes (internal link)
3. Live demo: webmaker.plus 

## Tasks
1. [x] Adjust titles (@chriteli1 )
2. [x] Make links (@chriteli1 )
3. [x] Hide pictures `display: none` (@chriteli1 )
4. [x] Prepare teaser copy (@skounis )
5. [x] Search for iconography (@skounis @evankarageorgos )

![image](https://user-images.githubusercontent.com/690575/195121577-40e9fc13-055c-47ef-85b9-f405f548528c.png)
